apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking

resources:
  - namespace.yml
  - secret.yml
  - configmap.yml
  - pv.yml
  - pvc.yml
  - db-deploy.yml
  - app-deploy.yaml

commonLabels:
  app: banking-backend
  managed-by: argocd

